// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";

import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // A CLI do Prisma (migrate, generate) usa DIRECT_URL (conexão direta,
  // sem pooler) — o pooler do Neon não sustenta o advisory lock das
  // migrations. O app em runtime usa DATABASE_URL (pooled) diretamente via
  // adapter em app/_lib/prisma.ts, sem depender deste arquivo.
  datasource: {
    url: env("DIRECT_URL"),
  },
});
