import "./globals.css";

import type { Metadata } from "next";
import { Mulish } from "next/font/google";

const mulish = Mulish({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${mulish.className} dark h-full antialiased`}>
        <div className="flex h-full flex-col overflow-hidden">{children}</div>
      </body>
    </html>
  );
}
